// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/infobloxopen/konk/test/apiserver/pkg/apis/contact/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeContacts implements ContactInterface
type FakeContacts struct {
	Fake *FakeContactV1alpha1
	ns   string
}

var contactsResource = schema.GroupVersionResource{Group: "contact.example.infoblox.com", Version: "v1alpha1", Resource: "contacts"}

var contactsKind = schema.GroupVersionKind{Group: "contact.example.infoblox.com", Version: "v1alpha1", Kind: "Contact"}

// Get takes name of the contact, and returns the corresponding contact object, and an error if there is any.
func (c *FakeContacts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Contact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(contactsResource, c.ns, name), &v1alpha1.Contact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Contact), err
}

// List takes label and field selectors, and returns the list of Contacts that match those selectors.
func (c *FakeContacts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ContactList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(contactsResource, contactsKind, c.ns, opts), &v1alpha1.ContactList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ContactList{ListMeta: obj.(*v1alpha1.ContactList).ListMeta}
	for _, item := range obj.(*v1alpha1.ContactList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested contacts.
func (c *FakeContacts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(contactsResource, c.ns, opts))

}

// Create takes the representation of a contact and creates it.  Returns the server's representation of the contact, and an error, if there is any.
func (c *FakeContacts) Create(ctx context.Context, contact *v1alpha1.Contact, opts v1.CreateOptions) (result *v1alpha1.Contact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(contactsResource, c.ns, contact), &v1alpha1.Contact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Contact), err
}

// Update takes the representation of a contact and updates it. Returns the server's representation of the contact, and an error, if there is any.
func (c *FakeContacts) Update(ctx context.Context, contact *v1alpha1.Contact, opts v1.UpdateOptions) (result *v1alpha1.Contact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(contactsResource, c.ns, contact), &v1alpha1.Contact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Contact), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeContacts) UpdateStatus(ctx context.Context, contact *v1alpha1.Contact, opts v1.UpdateOptions) (*v1alpha1.Contact, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(contactsResource, "status", c.ns, contact), &v1alpha1.Contact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Contact), err
}

// Delete takes name of the contact and deletes it. Returns an error if one occurs.
func (c *FakeContacts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(contactsResource, c.ns, name), &v1alpha1.Contact{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeContacts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(contactsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ContactList{})
	return err
}

// Patch applies the patch and returns the patched contact.
func (c *FakeContacts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Contact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(contactsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Contact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Contact), err
}
