version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: docker
  directory: "/test/apiserver"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/test/apiserver"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
