// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	example "github.com/infobloxopen/konk/test/apiserver/pkg/apis/example"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Contact)(nil), (*example.Contact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Contact_To_example_Contact(a.(*Contact), b.(*example.Contact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Contact)(nil), (*Contact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Contact_To_v1alpha1_Contact(a.(*example.Contact), b.(*Contact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContactList)(nil), (*example.ContactList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContactList_To_example_ContactList(a.(*ContactList), b.(*example.ContactList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.ContactList)(nil), (*ContactList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_ContactList_To_v1alpha1_ContactList(a.(*example.ContactList), b.(*ContactList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContactSpec)(nil), (*example.ContactSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContactSpec_To_example_ContactSpec(a.(*ContactSpec), b.(*example.ContactSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.ContactSpec)(nil), (*ContactSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_ContactSpec_To_v1alpha1_ContactSpec(a.(*example.ContactSpec), b.(*ContactSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContactStatus)(nil), (*example.ContactStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContactStatus_To_example_ContactStatus(a.(*ContactStatus), b.(*example.ContactStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.ContactStatus)(nil), (*ContactStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_ContactStatus_To_v1alpha1_ContactStatus(a.(*example.ContactStatus), b.(*ContactStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Contact_To_example_Contact(in *Contact, out *example.Contact, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContactSpec_To_example_ContactSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContactStatus_To_example_ContactStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Contact_To_example_Contact is an autogenerated conversion function.
func Convert_v1alpha1_Contact_To_example_Contact(in *Contact, out *example.Contact, s conversion.Scope) error {
	return autoConvert_v1alpha1_Contact_To_example_Contact(in, out, s)
}

func autoConvert_example_Contact_To_v1alpha1_Contact(in *example.Contact, out *Contact, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_example_ContactSpec_To_v1alpha1_ContactSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_example_ContactStatus_To_v1alpha1_ContactStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_example_Contact_To_v1alpha1_Contact is an autogenerated conversion function.
func Convert_example_Contact_To_v1alpha1_Contact(in *example.Contact, out *Contact, s conversion.Scope) error {
	return autoConvert_example_Contact_To_v1alpha1_Contact(in, out, s)
}

func autoConvert_v1alpha1_ContactList_To_example_ContactList(in *ContactList, out *example.ContactList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]example.Contact)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ContactList_To_example_ContactList is an autogenerated conversion function.
func Convert_v1alpha1_ContactList_To_example_ContactList(in *ContactList, out *example.ContactList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContactList_To_example_ContactList(in, out, s)
}

func autoConvert_example_ContactList_To_v1alpha1_ContactList(in *example.ContactList, out *ContactList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Contact)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_example_ContactList_To_v1alpha1_ContactList is an autogenerated conversion function.
func Convert_example_ContactList_To_v1alpha1_ContactList(in *example.ContactList, out *ContactList, s conversion.Scope) error {
	return autoConvert_example_ContactList_To_v1alpha1_ContactList(in, out, s)
}

func autoConvert_v1alpha1_ContactSpec_To_example_ContactSpec(in *ContactSpec, out *example.ContactSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ContactSpec_To_example_ContactSpec is an autogenerated conversion function.
func Convert_v1alpha1_ContactSpec_To_example_ContactSpec(in *ContactSpec, out *example.ContactSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContactSpec_To_example_ContactSpec(in, out, s)
}

func autoConvert_example_ContactSpec_To_v1alpha1_ContactSpec(in *example.ContactSpec, out *ContactSpec, s conversion.Scope) error {
	return nil
}

// Convert_example_ContactSpec_To_v1alpha1_ContactSpec is an autogenerated conversion function.
func Convert_example_ContactSpec_To_v1alpha1_ContactSpec(in *example.ContactSpec, out *ContactSpec, s conversion.Scope) error {
	return autoConvert_example_ContactSpec_To_v1alpha1_ContactSpec(in, out, s)
}

func autoConvert_v1alpha1_ContactStatus_To_example_ContactStatus(in *ContactStatus, out *example.ContactStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ContactStatus_To_example_ContactStatus is an autogenerated conversion function.
func Convert_v1alpha1_ContactStatus_To_example_ContactStatus(in *ContactStatus, out *example.ContactStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContactStatus_To_example_ContactStatus(in, out, s)
}

func autoConvert_example_ContactStatus_To_v1alpha1_ContactStatus(in *example.ContactStatus, out *ContactStatus, s conversion.Scope) error {
	return nil
}

// Convert_example_ContactStatus_To_v1alpha1_ContactStatus is an autogenerated conversion function.
func Convert_example_ContactStatus_To_v1alpha1_ContactStatus(in *example.ContactStatus, out *ContactStatus, s conversion.Scope) error {
	return autoConvert_example_ContactStatus_To_v1alpha1_ContactStatus(in, out, s)
}
