apiVersion: konk.infoblox.com/v1alpha1
kind: KonkService
metadata:
  name: example-konkservice
spec:
  konk:
    name: {{ .Values.konk.name }}
  service:
    name: {{ include "example-apiserver.fullname" . }}
  group: example.infoblox.com
  version: v1alpha1
  tlsVerify: true
  crds: |
{{ (.Files.Glob "crds/*").AsConfig | indent 4 }}
