apiVersion: konk.infoblox.com/v1alpha1
kind: KonkService
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "example-apiserver.labels" . | nindent 4 }}
spec:
  konk:
    name: {{ include "example-apiserver.konkname" . }}
  service:
    name: {{ include "example-apiserver.fullname" . }}
  group:
    name: example.infoblox.com
    kinds:
    - Contact
    verbs:
    - create
    - delete
    - get
    - watch
    - patch
    - list
    - update
  version: v1alpha1
  {{- with .Values.konkservice }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  crds: |
{{ (.Files.Glob "crds/*").AsConfig | indent 4 }}
