apiVersion: konk.infoblox.com/v1alpha1
kind: KonkService
metadata:
  name: {{ include "example-apiserver.konk-service-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "example-apiserver.labels" . | nindent 4 }}
spec:
  konk:
    name: {{ include "example-apiserver.konkname" . }}
    namespace: {{ .Values.konk.namespace }}
    scope: {{ .Values.konk.scope }}
  service:
    name: {{ include "example-apiserver.fullname" . }}
  group:
    name: example.infoblox.com
    kinds:
    - contact
    verbs:
    - create
    - delete
    - get
    - watch
    - patch
    - list
    - update
  version: v1alpha1
  {{- with .Values.konkservice }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
