apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "example-apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "example-apiserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
