apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.extensions.example.com
spec:
  scope: Namespaced
  group: extensions.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: websites
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of Konk
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                scope:
                  description: Defines the scope of access to this konk
                  type: string
                  pattern: '^cluster|namespace$'
            status:
              description: Status defines the observed state of Konk
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
  names:
    kind: Website
    singular: website
    plural: websites
    shortNames: ['ws']
