apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "konk.fullname" . }}-ingress-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
  secretName: {{ include "konk.fullname" . }}-ingress-client
  # SubjectAltName
  # TODO: change to view, update RBAC to allow view
  subject:
    organizations:
    - system:masters
  commonName: kubernetes-admin
  dnsNames:
  - admin
  issuerRef:
    name: {{ include "konk.fullname" . }}-ca-issuer
    kind: Issuer
