{{- with .Values.etcd }}
{{- if .operator }}
apiVersion: konk.infoblox.com/v1alpha1
kind: Etcd
metadata:
  name: {{ $.Release.Name }}-etcd
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "konk.labels" $ | nindent 4 }}
spec:
  {{ toYaml . | nindent 2 }}
  auth:
    rbac:
      enabled: false
    client:
      enableAuthentication: true
      secureTransport: true
      existingSecret: {{ include "konk.fullname" $ }}-etcd-cert
      certFilename: tls.crt
      certKeyFilename: tls.key
  {{- if $.Values.space.enabled }}
  global:
    imagePullSecrets:
      - {{ include "konk.fullname" $ }}-imagepullsecret
  {{- end }}
{{- end }}
{{- end }}
