{{- with .Values.etcd }}
{{- if .operator }}
apiVersion: konk.infoblox.com/v1alpha1
kind: Etcd
metadata:
  name: {{ $.Release.Name }}-etcd
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "konk.labels" $ | nindent 4 }}
spec:
  {{ toYaml . | nindent 2 }}
  auth:
    rbac:
      enabled: false
    client:
      secureTransport: true
      existingSecret: {{ include "konk.fullname" $ }}-etcd-cert
      certFilename: server.crt
      certKeyFilename: server.key
  {{- if $.Values.space.enabled }}
  global:
    imagePullSecrets:
      - {{ include "konk.fullname" $ }}-imagepullsecret
  {{- end }}
  # these probes don't work with self-signed certs because probe.sh doesn't set the cacert path in the $AUTH_OPTIONS
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
{{- end }}
{{- end }}
