apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "konk.fullname" . }}-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "konk.fullname" . }}-ca
