apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "konk.fullname" . }}-ca-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "konk.fullname" . }}-ca
