---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "konk.fullname" . }}-proxy-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
  secretName: {{ include "konk.fullname" . }}-proxy-client
  # SubjectAltName
  # TODO: change to view, update RBAC to allow view
  subject:
    organizations:
    - system:masters
  commonName: core
  dnsNames:
  - core
  issuerRef:
    name: {{ include "konk.fullname" . }}-selfsigned
    kind: Issuer
...
