# Front proxy client certificates.
# Reference: https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/

# Create a self signed CA certificate
apiVersion: {{ include "konk.certManagerApiVersion" . }}
kind: Issuer
metadata:
  name: {{ include "konk.fullname" . }}-requestheader-self-signed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: {{ include "konk.certManagerApiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "konk.fullname" . }}-requestheader-self-signed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
  secretName: {{ include "konk.fullname" . }}-requestheader-self-signed
  duration: 17520h #2y
  issuerRef:
    name: {{ include "konk.fullname" . }}-requestheader-self-signed
  commonName: "konk.infoblox"
  isCA: true
  revisionHistoryLimit: 1
---

# Create client certificates signed with above CA Certificate
apiVersion: {{ include "konk.certManagerApiVersion" . }}
kind: Issuer
metadata:
  name: {{ include "konk.fullname" . }}-requestheader
  {{- if eq .Values.scope "namespace" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
 ca:
   secretName: {{ include "konk.fullname" . }}-requestheader-self-signed
---
apiVersion: {{ include "konk.certManagerApiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "konk.fullname" . }}-requestheader-proxy-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
    component: proxy-client
spec:
  secretName: {{ include "konk.fullname" . }}-proxy-client
  # SubjectAltName
  # TODO: change to view, update RBAC to allow view
  subject:
    organizations:
    - system:masters
  commonName: core
  dnsNames:
  - core
  issuerRef:
    name: {{ include "konk.fullname" . }}-requestheader
    kind: Issuer
  revisionHistoryLimit: 1
...
