apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "konk.scope" . }}RoleBinding
metadata:
  name: {{ include "konk.fullname" . }}-certs-rb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "konk.scope" . }}Role
  name: {{ include "konk.fullname" . }}-certs-role
subjects:
- kind: ServiceAccount
  name: {{ include "konk.serviceAccountName" . }}
  {{- if eq .Values.scope "cluster" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
