{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "konk.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.space.enabled }}
imagePullSecrets:
- name: {{ template "konk.fullname" $ }}-imagepullsecret
{{- end }}
{{- end }}
