// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	contact "github.com/infobloxopen/konk/test/apiserver/pkg/apis/contact"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Contact)(nil), (*contact.Contact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Contact_To_contact_Contact(a.(*Contact), b.(*contact.Contact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*contact.Contact)(nil), (*Contact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_contact_Contact_To_v1alpha1_Contact(a.(*contact.Contact), b.(*Contact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContactList)(nil), (*contact.ContactList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContactList_To_contact_ContactList(a.(*ContactList), b.(*contact.ContactList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*contact.ContactList)(nil), (*ContactList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_contact_ContactList_To_v1alpha1_ContactList(a.(*contact.ContactList), b.(*ContactList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContactSpec)(nil), (*contact.ContactSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContactSpec_To_contact_ContactSpec(a.(*ContactSpec), b.(*contact.ContactSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*contact.ContactSpec)(nil), (*ContactSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_contact_ContactSpec_To_v1alpha1_ContactSpec(a.(*contact.ContactSpec), b.(*ContactSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContactStatus)(nil), (*contact.ContactStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContactStatus_To_contact_ContactStatus(a.(*ContactStatus), b.(*contact.ContactStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*contact.ContactStatus)(nil), (*ContactStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_contact_ContactStatus_To_v1alpha1_ContactStatus(a.(*contact.ContactStatus), b.(*ContactStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Contact_To_contact_Contact(in *Contact, out *contact.Contact, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContactSpec_To_contact_ContactSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContactStatus_To_contact_ContactStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Contact_To_contact_Contact is an autogenerated conversion function.
func Convert_v1alpha1_Contact_To_contact_Contact(in *Contact, out *contact.Contact, s conversion.Scope) error {
	return autoConvert_v1alpha1_Contact_To_contact_Contact(in, out, s)
}

func autoConvert_contact_Contact_To_v1alpha1_Contact(in *contact.Contact, out *Contact, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_contact_ContactSpec_To_v1alpha1_ContactSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_contact_ContactStatus_To_v1alpha1_ContactStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_contact_Contact_To_v1alpha1_Contact is an autogenerated conversion function.
func Convert_contact_Contact_To_v1alpha1_Contact(in *contact.Contact, out *Contact, s conversion.Scope) error {
	return autoConvert_contact_Contact_To_v1alpha1_Contact(in, out, s)
}

func autoConvert_v1alpha1_ContactList_To_contact_ContactList(in *ContactList, out *contact.ContactList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]contact.Contact)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ContactList_To_contact_ContactList is an autogenerated conversion function.
func Convert_v1alpha1_ContactList_To_contact_ContactList(in *ContactList, out *contact.ContactList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContactList_To_contact_ContactList(in, out, s)
}

func autoConvert_contact_ContactList_To_v1alpha1_ContactList(in *contact.ContactList, out *ContactList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Contact)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_contact_ContactList_To_v1alpha1_ContactList is an autogenerated conversion function.
func Convert_contact_ContactList_To_v1alpha1_ContactList(in *contact.ContactList, out *ContactList, s conversion.Scope) error {
	return autoConvert_contact_ContactList_To_v1alpha1_ContactList(in, out, s)
}

func autoConvert_v1alpha1_ContactSpec_To_contact_ContactSpec(in *ContactSpec, out *contact.ContactSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ContactSpec_To_contact_ContactSpec is an autogenerated conversion function.
func Convert_v1alpha1_ContactSpec_To_contact_ContactSpec(in *ContactSpec, out *contact.ContactSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContactSpec_To_contact_ContactSpec(in, out, s)
}

func autoConvert_contact_ContactSpec_To_v1alpha1_ContactSpec(in *contact.ContactSpec, out *ContactSpec, s conversion.Scope) error {
	return nil
}

// Convert_contact_ContactSpec_To_v1alpha1_ContactSpec is an autogenerated conversion function.
func Convert_contact_ContactSpec_To_v1alpha1_ContactSpec(in *contact.ContactSpec, out *ContactSpec, s conversion.Scope) error {
	return autoConvert_contact_ContactSpec_To_v1alpha1_ContactSpec(in, out, s)
}

func autoConvert_v1alpha1_ContactStatus_To_contact_ContactStatus(in *ContactStatus, out *contact.ContactStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ContactStatus_To_contact_ContactStatus is an autogenerated conversion function.
func Convert_v1alpha1_ContactStatus_To_contact_ContactStatus(in *ContactStatus, out *contact.ContactStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContactStatus_To_contact_ContactStatus(in, out, s)
}

func autoConvert_contact_ContactStatus_To_v1alpha1_ContactStatus(in *contact.ContactStatus, out *ContactStatus, s conversion.Scope) error {
	return nil
}

// Convert_contact_ContactStatus_To_v1alpha1_ContactStatus is an autogenerated conversion function.
func Convert_contact_ContactStatus_To_v1alpha1_ContactStatus(in *contact.ContactStatus, out *ContactStatus, s conversion.Scope) error {
	return autoConvert_contact_ContactStatus_To_v1alpha1_ContactStatus(in, out, s)
}
