# permissions for end users to view konks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konk-viewer-role
rules:
- apiGroups:
  - infoblox.com
  resources:
  - konks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infoblox.com
  resources:
  - konks/status
  verbs:
  - get
