# permissions for end users to view konkservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konkservice-viewer-role
rules:
- apiGroups:
  - konk.infoblox.com
  resources:
  - konkservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konk.infoblox.com
  resources:
  - konkservices/status
  verbs:
  - get
