# permissions for end users to edit konkservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konkservice-editor-role
rules:
- apiGroups:
  - konk.infoblox.com
  resources:
  - konkservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konk.infoblox.com
  resources:
  - konkservices/status
  verbs:
  - get
