apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "konk.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/provision.sh").AsConfig | indent 2 }}
