apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "konk.fullname" . }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "konk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "konk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "konk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/kube-apiserver
          args:
            - --etcd-cafile=/etc/kubernetes/pki/apiserver/etcd/ca.pem
            - --etcd-certfile=/etc/kubernetes/pki/apiserver/etcd/cert.pem
            - --etcd-keyfile=/etc/kubernetes/pki/apiserver/etcd/key.pem
            - --etcd-servers=https://127.0.0.1:4001 # TODO: provision etcd
            # TODO: mount certs
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/kubernetes/pki/apiserver/etcd
            name: etcd-client-certs
            readOnly: true
      volumes:
      - name: etcd-client-certs
        secret:
          defaultMode: 256
          secretName: {{ include "konk.fullname" . }}-etcd-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
