{{- /* TODO: replace with kubeadm certs */ -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "konk.fullname" . }}-etcd-cert
  labels:
    {{- include "konk.labels" . | nindent 4 }}
data:
{{- $ca := genCA "konk-ca" 365 }}
{{- $cert := genSignedCert "root" ( list "127.0.0.1" ) ( list ( printf "%s-%s" .Release.Name "etcd-headless") ) 365 $ca }}
  ca.pem: {{ $ca.Cert | b64enc }}
  cert.pem: {{ $cert.Cert | b64enc }}
  key.pem: {{ $cert.Key | b64enc }}
