apiVersion: v1
kind: Pod
metadata:
  name: {{ include "konk.fullname" . }}-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ include "konk.serviceAccountName" . }}
  containers:
  - name: kind
    securityContext:
      {{- toYaml .Values.kind.securityContext | nindent 6 }}
    image: "{{ .Values.kind.image.repository }}:{{ .Values.kind.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.kind.image.pullPolicy }}
    command:
      - bash
    args:
      - /scripts/provision.sh
    env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: FULLNAME
        value: {{ include "konk.fullname" . }}
      - name: LABELS
        value: {{ (include "konk.selectorLabels" .) | replace ": " "=" | replace "\n" " " }}
      - name: RELEASE
        value: {{ .Release.Name }}
    resources:
      {{- toYaml .Values.kind.resources | nindent 6 }}
    volumeMounts:
    - mountPath: /scripts/
      name: scripts
      readOnly: true
  volumes:
  - name: scripts
    configMap:
      name: {{ include "konk.fullname" . }}-scripts
      defaultMode: 0777
  restartPolicy: OnFailure
