apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "konk.fullname" . }}-certs-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "konk.fullname" . }}-certs-role
subjects:
- kind: ServiceAccount
  name: {{ include "konk.serviceAccountName" . }}
