apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "konk.fullname" . }}-certs-role
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - delete
    - list
    - watch
