apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "konk.fullname" . }}-certs-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - delete
    - list
    - patch
    - watch
