apiVersion: v2
name: etcd
description: A custom etcd Helm chart using upstream etcd images
version: 1.0.0
appVersion: "3.6.9"
type: application

keywords:
  - etcd
  - cluster
  - database
  - key-value

home: https://etcd.io
sources:
  - https://github.com/etcd-io/etcd

maintainers:
  - name: Infoblox
    email: cto-team@infoblox.com
