// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/infobloxopen/konk/test/apiserver/pkg/client/clientset_generated/clientset/typed/example/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeExampleV1alpha1 struct {
	*testing.Fake
}

func (c *FakeExampleV1alpha1) Contacts(namespace string) v1alpha1.ContactInterface {
	return &FakeContacts{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeExampleV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
