apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-service.fullname" . }}-kubectl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "api-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: apiservice
  template:
    metadata:
      labels:
        {{- include "api-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: apiservice
    spec:
      serviceAccountName: {{ include "api-service.serviceAccountName" . }}
      containers:
      - name: kind
        securityContext:
          {{- toYaml .Values.kind.securityContext | nindent 10 }}
        image: "{{ .Values.kind.image.repository }}:{{ .Values.kind.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.kind.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args: ["/mounts/deploy-api-service.sh; while true; do sleep 30; done;"]
        env:
          - name: SERVICENAME
            value: {{ .Values.service.name }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: FULLNAME
            value: {{ include "api-service.fullname" . }}-kubectl
          - name: KUBECONFIG
            value: /etc/kubernetes/admin.conf
        resources:
          {{- toYaml .Values.kind.resources | nindent 10 }}
        volumeMounts:
        - name: kubeconfig
          mountPath: "/etc/kubernetes"
          readOnly: true
        - name: ca-cert
          mountPath: "certs"
          readOnly: true
        - name: mounts
          mountPath: "mounts"
          readOnly: true
        - name: gen
          mountPath: "gen"
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{ .Values.konk.name }}-kubeconfig
      - name: ca-cert
        secret:
          secretName: {{ include "api-service.fullname" . }}-server
      - name: mounts
        configMap:
          name: {{ include "api-service.fullname" . }}-mounts
          defaultMode: 0777
      - name: gen
        emptyDir: {}
