apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "api-service.fullname" . }}-certs-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    - apps
    resources:
    - pods
    - secrets
    - deployments
    verbs:
    - create
    - get
    - delete
    - list
    - patch
    - watch
