apiVersion: konk.infoblox.com/v1alpha1
kind: KonkService
metadata:
  name: example-konkservice
spec:
  group:
    name: example.infoblox.com
    kinds:
    - Contact
    verbs:
    - create
    - update
    - get
    - list
    - delete
    - watch
  konk:
    name: example
  service:
    name: test
  version: v1alpha1
