apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "konk-service.fullname" . | trunc 46 | trimSuffix "-" }}-apiservice-test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "konk-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: apiservice-test
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apiservice-configmap.yaml") . | sha256sum }}
        checksum/values: {{ print .Values | sha256sum }}
      labels:
        {{- include "konk-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: apiservice-test
    spec:
      serviceAccountName: {{ include "konk-service.serviceAccountName" . }}
      containers:
      - name: apiservice-test
        securityContext:
          {{- toYaml .Values.kind.securityContext | nindent 10 }}
        image: "{{ .Values.kind.image.repository }}:{{ .Values.kind.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.kind.image.pullPolicy }}
        command: ["/usr/local/bin/konk-service", "test-apiservice"]
        env:
          - name: KUBECONFIG
            value: /etc/kubernetes/admin.conf
          - name: VERSION
            value: {{ .Values.version }}
          - name: GROUP
            value: {{ .Values.group.name }}
        resources:
          {{- toYaml .Values.kind.resources | nindent 10 }}
        volumeMounts:
        - name: kubeconfig
          mountPath: "/etc/kubernetes"
          readOnly: true
        - name: tmp
          mountPath: "/tmp"
        readinessProbe:
          exec:
            command: ["/usr/local/bin/konk-service", "healthz", "/tmp/healthy"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{ include "konk-service.fullname" . }}-kubeconfig
      - name: tmp
        emptyDir: {}
