apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "konk-service.fullname" . }}-mounts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
data:
  api-service.yaml.in: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {{` {{ NAMESPACE }} `}}
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: {{` {{ SERVICENAME }} `}}
      namespace: {{` {{ NAMESPACE }} `}}
    spec:
      type: ExternalName
      externalName: {{` {{ SERVICENAME }} `}}.{{` {{ NAMESPACE }} `}}
    ---
    apiVersion: apiregistration.k8s.io/v1
    kind: APIService
    metadata:
      name: {{ .Values.version }}.{{ .Values.group.name }}
      {{- with .Values.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.insecureSkipTLSVerify }}
      insecureSkipTLSVerify: {{ .Values.insecureSkipTLSVerify }}
      {{- else }}
      caBundle: {{` {{ CERT }} `}}
      {{- end }}
      group: {{ .Values.group.name }}
      groupPriorityMinimum: 1000
      service:
        name: {{` {{ SERVICENAME }} `}}
        namespace: {{` {{ NAMESPACE }} `}}
      version: {{ .Values.version }}
      versionPriority: 100
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: {{ .Values.group.name }}-edit
      labels:
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rules:
      - apiGroups:
        - {{ .Values.group.name }}
        resources:
        {{- range .Values.group.kinds }}
        - {{ . | quote }}
        {{- end }}
        verbs:
        {{- range .Values.group.verbs }}
        - {{ . | quote }}
        {{- end }}

  delete-api-service.yaml.in: |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{` {{ SERVICENAME }} `}}
      namespace: {{` {{ NAMESPACE }} `}}
    spec:
      type: ExternalName
      externalName: {{` {{ SERVICENAME }} `}}.{{` {{ NAMESPACE }} `}}
    ---
    apiVersion: apiregistration.k8s.io/v1
    kind: APIService
    metadata:
      name: {{ .Values.version }}.{{ .Values.group.name }}
      {{- with .Values.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.insecureSkipTLSVerify }}
      insecureSkipTLSVerify: {{ .Values.insecureSkipTLSVerify }}
      {{- else }}
      caBundle: {{` {{ CERT }} `}}
      {{- end }}
      group: {{ .Values.group.name }}
      groupPriorityMinimum: 1000
      service:
        name: {{` {{ SERVICENAME }} `}}
        namespace: {{` {{ NAMESPACE }} `}}
      version: {{ .Values.version }}
      versionPriority: 100
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: {{ .Values.group.name }}-edit
      labels:
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rules:
      - apiGroups:
        - {{ .Values.group.name }}
        resources:
        {{- range .Values.group.kinds }}
        - {{ . | quote }}
        {{- end }}
        verbs:
        {{- range .Values.group.verbs }}
        - {{ . | quote }}
        {{- end }}
{{ if .Values.crds }}
  crds.yaml: |
{{ .Values.crds | indent 4 }}
{{ end }}
