{{- if not .Values.service.caSecretName }}
apiVersion: {{ include "konk-service.certManagerApiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "konk-service.fullname" . }}-server
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
spec:
  secretName: {{ include "konk-service.fullname" . }}-server
  duration: 8760h # 1y
  issuerRef:
    name: {{ include "konk-service.fullname" . }}-ca
  dnsNames:
  - {{ .Values.service.name }}
  - {{ .Values.service.name }}.{{ .Release.Namespace }}
  - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
  - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
