apiVersion: v1
kind: Pod
metadata:
  name: {{ include "konk-service.fullname" . }}-delete-apiservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
spec:
  serviceAccountName: {{ include "konk-service.serviceAccountName" . }}
  containers:
  - name: kind
    securityContext:
      {{- toYaml .Values.kind.securityContext | nindent 10 }}
    image: "{{ .Values.kind.image.repository }}:{{ .Values.kind.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.kind.image.pullPolicy }}
    command: ["/bin/bash", "-c"]
    args:
      - |
        while true
        do
          /mounts/delete-api-service.sh
          date
          sleep 30
        done
    env:
      - name: SERVICENAME
        value: {{ .Values.service.name }}
      - name: NAMESPACE
        value: {{ .Release.Namespace }}
      - name: KUBECONFIG
        value: /etc/kubernetes/admin.conf
    resources:
      {{- toYaml .Values.kind.resources | nindent 10 }}
    volumeMounts:
    - name: kubeconfig
      mountPath: "/etc/kubernetes"
      readOnly: true
    - name: ca-cert
      mountPath: "certs"
      readOnly: true
    - name: mounts
      mountPath: "mounts"
      readOnly: true
    - name: gen
      mountPath: "gen"
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: kubeconfig
    secret:
      secretName: {{ include "konk-service.fullname" . }}-kubeconfig
  - name: ca-cert
    secret:
      secretName: {{ if .Values.service.caSecretName -}}
      {{ .Values.service.caSecretName }}
      {{- else -}}
      {{ include "konk-service.fullname" . }}-server
      {{- end }}
  - name: mounts
    configMap:
      name: {{ include "konk-service.fullname" . }}-mounts
      defaultMode: 0777
  - name: gen
    emptyDir: {}
