apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "konk-service.fullname" . | trunc 43 | trimSuffix "-" }}-delete-apiservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
  annotations:
    {{- include "konk-service.helmAnnotations" . | nindent 4 }}
    helm.sh/hook: pre-delete
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "konk-service.serviceAccountName" . }}
      containers:
      - name: delete-apiservice
        securityContext:
          {{- toYaml .Values.kind.securityContext | nindent 10 }}
        image: "{{ .Values.kind.image.repository }}:{{ .Values.kind.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.kind.image.pullPolicy }}
        command: ["/usr/local/bin/konk-service", "delete-apiservice"]
        env:
          - name: SERVICENAME
            value: {{ .Values.service.name }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: KUBECONFIG
            value: /etc/kubernetes/admin.conf
          - name: CERT_DIR
            value: /certs
          - name: MANIFESTS
            valueFrom:
              configMapKeyRef:
                name: {{ include "konk-service.fullname" . }}-mounts
                key: delete-api-service.yaml.in
        resources:
          {{- toYaml .Values.kind.resources | nindent 10 }}
        volumeMounts:
        - name: kubeconfig
          mountPath: "/etc/kubernetes"
          readOnly: true
        - name: ca-cert
          mountPath: "/certs"
          readOnly: true
        - name: tmp
          mountPath: "/tmp"
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{ include "konk-service.fullname" . }}-kubeconfig
      - name: ca-cert
        secret:
          secretName: {{ if .Values.service.caSecretName -}}
          {{ .Values.service.caSecretName }}
          {{- else -}}
          {{ include "konk-service.fullname" . }}-server
          {{- end }}
      - name: tmp
        emptyDir: {}
