apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "konk-service.fullname" . }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
spec:
  secretName: {{ include "konk-service.fullname" . }}-kubeconfig
  subject:
    organizations:
    - system:masters
  commonName: kubernetes-admin
  dnsNames:
  - admin
  issuerRef:
    name: {{ .Values.konk.name }}-kubeadm-ca
    kind: {{ if eq .Values.konk.scope "cluster" }}Cluster{{ end }}Issuer
