apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "konk-service.fullname" . }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - delete
    - list
    - patch
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "konk-service.fullname" . }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "konk-service.fullname" . }}-kubeconfig
subjects:
- kind: ServiceAccount
  name: {{ include "konk-service.serviceAccountName" . }}
