apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "konk-service.fullname" . | trunc 52 | trimSuffix "-" }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "konk-service.helmAnnotations" . | nindent 4 }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "konk-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kubeconfig
  template:
    metadata:
      annotations:
        checksum/values: {{ print .Values | sha256sum }}
      labels:
        {{- include "konk-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kubeconfig
    spec:
      serviceAccountName: {{ include "konk-service.serviceAccountName" . }}
      containers:
      - name: kubeconfig
        securityContext:
          {{- toYaml .Values.kind.securityContext | nindent 10 }}
        image: "{{ .Values.kind.image.repository }}:{{ .Values.kind.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.kind.image.pullPolicy }}
        command: ["/usr/local/bin/konk-service", "reconcile-kubeconfig"]
        env:
          - name: KUBECONFIG_PATH
            value: /etc/kubernetes/admin.conf
          - name: LABELS
            value: {{ (include "konk-service.selectorLabels" .) | replace ": " "=" | replace "\n" " " }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: FULLNAME
            value: {{ include "konk-service.fullname" . }}
          - name: KONK_NAME
            value: {{ .Values.konk.name }}
          - name: KONK_FQDN
            value: {{ include "konk-service.konkfqdn" . }}
          - name: CERT_DIR
            value: /tmp/certs
        volumeMounts:
        - name: kubeconfig
          mountPath: "/etc/kubernetes"
        - name: kubeconfig-cert
          mountPath: /tmp/certs
          readOnly: true
        - name: tmp
          mountPath: /tmp
        resources:
          {{- toYaml .Values.kind.resources | nindent 10 }}
        readinessProbe:
          exec:
            command: ["/usr/local/bin/konk-service", "healthz", "/tmp/status"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: kubeconfig
        emptyDir: {}
      - name: kubeconfig-cert
        secret:
          secretName: {{ include "konk-service.fullname" . }}-kubeconfig-cert
      - name: tmp
        emptyDir: {}
