{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "konk-service.serviceAccountName" . }}
  labels:
    {{- include "konk-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.space.enabled }}
imagePullSecrets:
- name: {{ template "konk-service.fullname" $ }}-imagepullsecret
{{- end }}
{{- end }}
