// Code generated by apiregister-gen. DO NOT EDIT.

package install

import (
	"github.com/infobloxopen/konk/test/apiserver/pkg/apis/contact"
	"github.com/infobloxopen/konk/test/apiserver/pkg/apis/contact/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

func init() {
	Install(builders.Scheme)
}

func Install(scheme *runtime.Scheme) {
	utilruntime.Must(v1alpha1.AddToScheme(scheme))
	utilruntime.Must(contact.AddToScheme(scheme))
	utilruntime.Must(addKnownTypes(scheme))
}

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(contact.SchemeGroupVersion,
		&contact.Contact{},
		&contact.ContactList{},
	)
	return nil
}
