// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ContactListerExpansion allows custom methods to be added to
// ContactLister.
type ContactListerExpansion interface{}

// ContactNamespaceListerExpansion allows custom methods to be added to
// ContactNamespaceLister.
type ContactNamespaceListerExpansion interface{}
