// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/infobloxopen/konk/test/apiserver/pkg/apis/contact/v1alpha1"
	"github.com/infobloxopen/konk/test/apiserver/pkg/client/clientset_generated/clientset/scheme"
	rest "k8s.io/client-go/rest"
)

type ContactV1alpha1Interface interface {
	RESTClient() rest.Interface
	ContactsGetter
}

// ContactV1alpha1Client is used to interact with features provided by the contact.example.infoblox.com group.
type ContactV1alpha1Client struct {
	restClient rest.Interface
}

func (c *ContactV1alpha1Client) Contacts(namespace string) ContactInterface {
	return newContacts(c, namespace)
}

// NewForConfig creates a new ContactV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*ContactV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ContactV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new ContactV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ContactV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ContactV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *ContactV1alpha1Client {
	return &ContactV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ContactV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
