# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
commonAnnotations:
  helm.sh/hook: crd-install
  # does not fail to install if resource already exists
  helm.sh/hook-delete-policy: before-hook-creation
resources:
- bases/konk.infoblox.com_konks.yaml
- bases/konk.infoblox.com_konkservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource
