apiVersion: konk.infoblox.com/v1alpha1
kind: KonkService
metadata:
  name: example-konkservice
spec:
  konk:
    name: example-konk
  service:
    name: runner-example-apiserver
  group: example.infoblox.com
  version: v1alpha1
  crds: |
{{ (.Files.Glob "crds/*").AsConfig | indent 4 }}
