apiVersion: konk.infoblox.com/v1alpha1
kind: KonkService
metadata:
  name: example-konkservice
spec:
  konk:
    name: example
  service:
    name: test
  crds: |
{{ (.Files.Glob "crds/*").AsConfig | indent 4 }}
