// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/infobloxopen/konk/test/apiserver/pkg/apis/example/v1alpha1"
	scheme "github.com/infobloxopen/konk/test/apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ContactsGetter has a method to return a ContactInterface.
// A group's client should implement this interface.
type ContactsGetter interface {
	Contacts(namespace string) ContactInterface
}

// ContactInterface has methods to work with Contact resources.
type ContactInterface interface {
	Create(ctx context.Context, contact *v1alpha1.Contact, opts v1.CreateOptions) (*v1alpha1.Contact, error)
	Update(ctx context.Context, contact *v1alpha1.Contact, opts v1.UpdateOptions) (*v1alpha1.Contact, error)
	UpdateStatus(ctx context.Context, contact *v1alpha1.Contact, opts v1.UpdateOptions) (*v1alpha1.Contact, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Contact, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ContactList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Contact, err error)
	ContactExpansion
}

// contacts implements ContactInterface
type contacts struct {
	client rest.Interface
	ns     string
}

// newContacts returns a Contacts
func newContacts(c *ExampleV1alpha1Client, namespace string) *contacts {
	return &contacts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the contact, and returns the corresponding contact object, and an error if there is any.
func (c *contacts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Contact, err error) {
	result = &v1alpha1.Contact{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("contacts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Contacts that match those selectors.
func (c *contacts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ContactList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ContactList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("contacts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested contacts.
func (c *contacts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("contacts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a contact and creates it.  Returns the server's representation of the contact, and an error, if there is any.
func (c *contacts) Create(ctx context.Context, contact *v1alpha1.Contact, opts v1.CreateOptions) (result *v1alpha1.Contact, err error) {
	result = &v1alpha1.Contact{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("contacts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(contact).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a contact and updates it. Returns the server's representation of the contact, and an error, if there is any.
func (c *contacts) Update(ctx context.Context, contact *v1alpha1.Contact, opts v1.UpdateOptions) (result *v1alpha1.Contact, err error) {
	result = &v1alpha1.Contact{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("contacts").
		Name(contact.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(contact).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *contacts) UpdateStatus(ctx context.Context, contact *v1alpha1.Contact, opts v1.UpdateOptions) (result *v1alpha1.Contact, err error) {
	result = &v1alpha1.Contact{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("contacts").
		Name(contact.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(contact).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the contact and deletes it. Returns an error if one occurs.
func (c *contacts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("contacts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *contacts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("contacts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched contact.
func (c *contacts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Contact, err error) {
	result = &v1alpha1.Contact{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("contacts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
