{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    {{- include "etcd.helmAnnotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "etcd.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.podMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
{{- end }}
