apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.headlessServiceName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "etcd.helmAnnotations" . | nindent 4 }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: {{ .Values.service.clientPortNameOverride | default "client" }}
      port: {{ .Values.service.port }}
      targetPort: client
      protocol: TCP
    - name: {{ .Values.service.peerPortNameOverride | default "peer" }}
      port: {{ .Values.service.peerPort }}
      targetPort: peer
      protocol: TCP
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
