apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    {{- include "etcd.helmAnnotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.clientPortNameOverride | default "client" }}
      port: {{ .Values.service.port }}
      targetPort: client
      protocol: TCP
    - name: {{ .Values.service.peerPortNameOverride | default "peer" }}
      port: {{ .Values.service.peerPort }}
      targetPort: peer
      protocol: TCP
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
