# kubernetes $(K8S_RELEASE)
apiserver:
  image:
    tag: $(K8S_RELEASE)-$(GIT_SHORT)
etcd:
  image:
    tag: $(ETCD_VERSION)
provision:
  image:
    tag: $(GIT_VERSION)
kind:
  image:
    tag: $(GIT_VERSION)
