name: Release Charts

on:
  push:
    branches:
      - main
      - release-charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3.5
      - run: make package
      - run: git checkout gh-pages
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release Charts
        run: |
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          charts_repo_url="https://$owner.github.io/$repo"
          helm repo index --url "$charts_repo_url" --merge index.yaml .
          git add index.yaml *.tgz
          git commit -m "push charts"
          git push
